version: '3'
services:
  driver:
    build: web
    ports:
      - "27080:80"
    volumes:
      - ../docs:/var/www/html/
      - ../docs/404.html:/var/www/error/404.html
    environment:
      TZ: Asia/Tokyo
    working_dir: /var/www/html/
