name: Deployment

on:
  # トリガーブランチ
  push:
    branches: ["main"]

  # ワークフローを手動実行可能にする設定
  workflow_dispatch:

permissions:
  # リポジトリのアクセス権限
  contents: read

  # GitHub Pagesのアクセス権限
  pages: write

  # IDトークンを発行
  id-token: write

# 同じpagesグループのジョブは同時に実行させない
# 同時デプロイによる競合やリソースの無駄遣いを防ぐために、既存のジョブをキャンセルする
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      # https://github.com/pnpm/action-setup
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      # https://github.com/actions/cache
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # https://github.com/actions/configure-pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run generate:github

      # https://github.com/actions/upload-pages-artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # https://github.com/actions/deploy-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
